import NodeMailer from "nodemailer";

const user = {
  mail: "studie.konto.420@gmail.com",
  password: "wibecilyptpfjlga",
};

const message = {
  text: "This is an autogenerated mail 🏴‍☠️",
};

let transporter = NodeMailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false, // true for 465, false for other ports
  auth: {
    user: user.mail, 
    pass: user.password,
  },
});

// send mail with defined transport object
export function sendMail(reciever) {
  return new Promise(async (resolve, reject) => {
    try {
      const mail = await transporter.sendMail({
        from: `"Study mail 🎃 👻" <${user.mail}>`, // sender address
        to: `${reciever.mail}`, // list of receivers
        subject: `Hello ${reciever.name}`, // Subject line
        text: message.text, // plain text body
        html: `<b>${message.text}</b>`, // html body
      });
      resolve(mail);
    } catch (err) {
      reject("Error code 1");
    }
  });
}
