import NodeMailer from "nodemailer";

const user = {
  mail: "studie.konto.420@gmail.com",
  password: "wibecilyptpfjlga", //
};

const message = {
  text: "This is an autogenerated mail 🏴‍☠️",
};

let transporter = NodeMailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false, 
  auth: {
    user: user.mail, 
    pass: user.password,
  },
});

// send mail 
export function sendMail(reciever) {
  return new Promise(async (resolve, reject) => {
    try {
      const mail = await transporter.sendMail({
        from: `"Study mail 🎃 👻" <${user.mail}>`,
        to: `${reciever.mail}`, 
        subject: `Hello ${reciever.name}`, 
        text: message.text, 
        html: `<b>${message.text}</b>`,
      });
      resolve(mail);
    } catch (err) {
      reject("Error code 1");
    }
  });
}
